# Generated by Django 5.0.6 on 2024-05-21 03:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_remove_register_first_name_remove_register_last_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("dob", models.DateField()),
                ("password", models.CharField(max_length=128)),
            ],
        ),
    ]
